[package]
name = "moldy"
version = "0.1.0"
edition = "2021"
description = "A minimal templating CLI for copying template directories"
readme = "README.md"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
toml = "1.1.2+spec-1.1.0"
serde = { version = "1.0", features = ["derive"] }
colored = "3.1.1"
walkdir = "2.5"
shellexpand = "3.0"
dirs = "5.0"

[dev-dependencies]
tempfile = "3.10"
